# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/workspace/iotgate/hiredis-vip

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/workspace/iotgate/hiredis-vip

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/workspace/iotgate/hiredis-vip/CMakeFiles /root/workspace/iotgate/hiredis-vip/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/workspace/iotgate/hiredis-vip/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hiredis-vip

# Build rule for target.
hiredis-vip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hiredis-vip
.PHONY : hiredis-vip

# fast build rule for target.
hiredis-vip/fast:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/build
.PHONY : hiredis-vip/fast

adlist.o: adlist.c.o
.PHONY : adlist.o

# target to build an object file
adlist.c.o:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/adlist.c.o
.PHONY : adlist.c.o

adlist.i: adlist.c.i
.PHONY : adlist.i

# target to preprocess a source file
adlist.c.i:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/adlist.c.i
.PHONY : adlist.c.i

adlist.s: adlist.c.s
.PHONY : adlist.s

# target to generate assembly for a file
adlist.c.s:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/adlist.c.s
.PHONY : adlist.c.s

alloc.o: alloc.c.o
.PHONY : alloc.o

# target to build an object file
alloc.c.o:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/alloc.c.o
.PHONY : alloc.c.o

alloc.i: alloc.c.i
.PHONY : alloc.i

# target to preprocess a source file
alloc.c.i:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/alloc.c.i
.PHONY : alloc.c.i

alloc.s: alloc.c.s
.PHONY : alloc.s

# target to generate assembly for a file
alloc.c.s:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/alloc.c.s
.PHONY : alloc.c.s

async.o: async.c.o
.PHONY : async.o

# target to build an object file
async.c.o:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/async.c.o
.PHONY : async.c.o

async.i: async.c.i
.PHONY : async.i

# target to preprocess a source file
async.c.i:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/async.c.i
.PHONY : async.c.i

async.s: async.c.s
.PHONY : async.s

# target to generate assembly for a file
async.c.s:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/async.c.s
.PHONY : async.c.s

command.o: command.c.o
.PHONY : command.o

# target to build an object file
command.c.o:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/command.c.o
.PHONY : command.c.o

command.i: command.c.i
.PHONY : command.i

# target to preprocess a source file
command.c.i:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/command.c.i
.PHONY : command.c.i

command.s: command.c.s
.PHONY : command.s

# target to generate assembly for a file
command.c.s:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/command.c.s
.PHONY : command.c.s

crc16.o: crc16.c.o
.PHONY : crc16.o

# target to build an object file
crc16.c.o:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/crc16.c.o
.PHONY : crc16.c.o

crc16.i: crc16.c.i
.PHONY : crc16.i

# target to preprocess a source file
crc16.c.i:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/crc16.c.i
.PHONY : crc16.c.i

crc16.s: crc16.c.s
.PHONY : crc16.s

# target to generate assembly for a file
crc16.c.s:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/crc16.c.s
.PHONY : crc16.c.s

dict.o: dict.c.o
.PHONY : dict.o

# target to build an object file
dict.c.o:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/dict.c.o
.PHONY : dict.c.o

dict.i: dict.c.i
.PHONY : dict.i

# target to preprocess a source file
dict.c.i:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/dict.c.i
.PHONY : dict.c.i

dict.s: dict.c.s
.PHONY : dict.s

# target to generate assembly for a file
dict.c.s:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/dict.c.s
.PHONY : dict.c.s

hiarray.o: hiarray.c.o
.PHONY : hiarray.o

# target to build an object file
hiarray.c.o:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/hiarray.c.o
.PHONY : hiarray.c.o

hiarray.i: hiarray.c.i
.PHONY : hiarray.i

# target to preprocess a source file
hiarray.c.i:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/hiarray.c.i
.PHONY : hiarray.c.i

hiarray.s: hiarray.c.s
.PHONY : hiarray.s

# target to generate assembly for a file
hiarray.c.s:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/hiarray.c.s
.PHONY : hiarray.c.s

hircluster.o: hircluster.c.o
.PHONY : hircluster.o

# target to build an object file
hircluster.c.o:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/hircluster.c.o
.PHONY : hircluster.c.o

hircluster.i: hircluster.c.i
.PHONY : hircluster.i

# target to preprocess a source file
hircluster.c.i:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/hircluster.c.i
.PHONY : hircluster.c.i

hircluster.s: hircluster.c.s
.PHONY : hircluster.s

# target to generate assembly for a file
hircluster.c.s:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/hircluster.c.s
.PHONY : hircluster.c.s

hiredis.o: hiredis.c.o
.PHONY : hiredis.o

# target to build an object file
hiredis.c.o:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/hiredis.c.o
.PHONY : hiredis.c.o

hiredis.i: hiredis.c.i
.PHONY : hiredis.i

# target to preprocess a source file
hiredis.c.i:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/hiredis.c.i
.PHONY : hiredis.c.i

hiredis.s: hiredis.c.s
.PHONY : hiredis.s

# target to generate assembly for a file
hiredis.c.s:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/hiredis.c.s
.PHONY : hiredis.c.s

hiutil.o: hiutil.c.o
.PHONY : hiutil.o

# target to build an object file
hiutil.c.o:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/hiutil.c.o
.PHONY : hiutil.c.o

hiutil.i: hiutil.c.i
.PHONY : hiutil.i

# target to preprocess a source file
hiutil.c.i:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/hiutil.c.i
.PHONY : hiutil.c.i

hiutil.s: hiutil.c.s
.PHONY : hiutil.s

# target to generate assembly for a file
hiutil.c.s:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/hiutil.c.s
.PHONY : hiutil.c.s

net.o: net.c.o
.PHONY : net.o

# target to build an object file
net.c.o:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/net.c.o
.PHONY : net.c.o

net.i: net.c.i
.PHONY : net.i

# target to preprocess a source file
net.c.i:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/net.c.i
.PHONY : net.c.i

net.s: net.c.s
.PHONY : net.s

# target to generate assembly for a file
net.c.s:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/net.c.s
.PHONY : net.c.s

read.o: read.c.o
.PHONY : read.o

# target to build an object file
read.c.o:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/read.c.o
.PHONY : read.c.o

read.i: read.c.i
.PHONY : read.i

# target to preprocess a source file
read.c.i:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/read.c.i
.PHONY : read.c.i

read.s: read.c.s
.PHONY : read.s

# target to generate assembly for a file
read.c.s:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/read.c.s
.PHONY : read.c.s

sds.o: sds.c.o
.PHONY : sds.o

# target to build an object file
sds.c.o:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/sds.c.o
.PHONY : sds.c.o

sds.i: sds.c.i
.PHONY : sds.i

# target to preprocess a source file
sds.c.i:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/sds.c.i
.PHONY : sds.c.i

sds.s: sds.c.s
.PHONY : sds.s

# target to generate assembly for a file
sds.c.s:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/sds.c.s
.PHONY : sds.c.s

sockcompat.o: sockcompat.c.o
.PHONY : sockcompat.o

# target to build an object file
sockcompat.c.o:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/sockcompat.c.o
.PHONY : sockcompat.c.o

sockcompat.i: sockcompat.c.i
.PHONY : sockcompat.i

# target to preprocess a source file
sockcompat.c.i:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/sockcompat.c.i
.PHONY : sockcompat.c.i

sockcompat.s: sockcompat.c.s
.PHONY : sockcompat.s

# target to generate assembly for a file
sockcompat.c.s:
	$(MAKE) -f CMakeFiles/hiredis-vip.dir/build.make CMakeFiles/hiredis-vip.dir/sockcompat.c.s
.PHONY : sockcompat.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... hiredis-vip"
	@echo "... rebuild_cache"
	@echo "... adlist.o"
	@echo "... adlist.i"
	@echo "... adlist.s"
	@echo "... alloc.o"
	@echo "... alloc.i"
	@echo "... alloc.s"
	@echo "... async.o"
	@echo "... async.i"
	@echo "... async.s"
	@echo "... command.o"
	@echo "... command.i"
	@echo "... command.s"
	@echo "... crc16.o"
	@echo "... crc16.i"
	@echo "... crc16.s"
	@echo "... dict.o"
	@echo "... dict.i"
	@echo "... dict.s"
	@echo "... hiarray.o"
	@echo "... hiarray.i"
	@echo "... hiarray.s"
	@echo "... hircluster.o"
	@echo "... hircluster.i"
	@echo "... hircluster.s"
	@echo "... hiredis.o"
	@echo "... hiredis.i"
	@echo "... hiredis.s"
	@echo "... hiutil.o"
	@echo "... hiutil.i"
	@echo "... hiutil.s"
	@echo "... net.o"
	@echo "... net.i"
	@echo "... net.s"
	@echo "... read.o"
	@echo "... read.i"
	@echo "... read.s"
	@echo "... sds.o"
	@echo "... sds.i"
	@echo "... sds.s"
	@echo "... sockcompat.o"
	@echo "... sockcompat.i"
	@echo "... sockcompat.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

